# Generated by Django 4.1.6 on 2023-11-18 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medassistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='prescriptionpdf',
            field=models.ImageField(default=datetime.datetime(2023, 11, 18, 17, 45, 18, 90885, tzinfo=datetime.timezone.utc), upload_to='static/'),
            preserve_default=False,
        ),
    ]
