# Generated by Django 4.1.6 on 2023-11-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medassistapp', '0002_answers_prescriptionpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='prescriptionpdf',
        ),
    ]
