# Generated by Django 4.1.6 on 2023-11-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medassistapp', '0003_remove_answers_prescriptionpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='prespdf',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
