# Generated by Django 4.1.6 on 2023-11-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medassistapp', '0004_answers_prespdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='prespdf',
        ),
    ]
