# Generated by Django 4.1.6 on 2023-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medassistapp', '0005_remove_answers_prespdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='prescriptionpdf',
            field=models.ImageField(blank=True, default=None, upload_to='static/', verbose_name='Prescription PDF'),
        ),
    ]
