# Generated by Django 4.1.6 on 2023-11-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medassistapp', '0006_answers_prescriptionpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='razorpayid',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
