# Generated by Django 4.1.6 on 2023-11-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medassistapp', '0007_answers_razorpayid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(default='', max_length=400),
        ),
    ]
