# Generated by Django 4.1.6 on 2023-11-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medassistapp', '0008_alter_prescription_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='razorpayid',
            field=models.CharField(blank=True, default=None, max_length=4000, verbose_name='Payment'),
        ),
    ]
